---
- name: install sgx drivers
  command:
    cmd: 'apt-get install -y {{ role_path }}/files/sgx-libgbm.deb {{ role_path }}/files/sgx-ti335x-userspace-1.14.3699939_1.1.deb'
- name: copy powervr.ini file
  copy:
    src: '{{ role_path }}/files/powervr.ini'
    dest: /etc/powervr.ini
    mode: 755
    owner: root
- name: enable sgx-startup
  service:
    name: sgx-startup
    enabled: yes
- name: create console-setup
  file:
    path: /etc/default/console-setup
    owner: root
    group: root
    state: touch
- name: set font in console-setup
  lineinfile:
    path: /etc/default/console-setup
    regex: 'FONT='
    line: 'FONT=Lat15-Terminus12x6.psf.gz'

- name: set colors in terminal for sessions
  lineinfile:
    path: /etc/profile
    line: 'force_color_prompt=yes'
    state: present

- name: set colors in terminal for sessions
  lineinfile:
    path: /etc/profile
    line: 'force_color_prompt=no'
    state: absent

- name: create bb-boot file
  file:
    path: /etc/default/bb-boot
    state: touch

- name: disable usb image file
  lineinefile:
    path: /etc/default/bb-boot
    line: 'USB_IMAGE_FILE_DISABLED=yes'
    state: present
