---
- name: remove login info
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: Register ReFactor version
  script:
    cmd: '{{ role_path }}/files/get_refactor_version.sh'
  register: version

- name: upgrade packages
  apt:
    upgrade: dist

- name: remove unneeded packages
  apt:
    pkg:
    - nginx
    - hostapd
    - libgtk3-common
    - grub
    - javascript-common
    state: absent
    autoremove: yes

- name: Replicape - update RCN scripts
  command:
    chdir: /opt/scripts
    cmd: 'git pull'
  when: platform == 'replicape'

- name: install debconf-utils and curl
  apt:
    pkg:
      - debconf-utils
      - curl
      - firmware-realtek
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-pip
    - python3-pip
    - python-dev
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - unzip
    - cpufrequtils
    - pkg-config
    - python3-dev
    - pkg-config
    state: present
    autoremove: yes
    autoclean: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present

- name: remove unneeded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/
    - /root/.c9
    - /usr/lib/node_modules
    - /usr/local/lib/node_modules
    - /var/lib/cloud9
    - /var/cache/doc*

- name: create dogtag
  file:
    path: '/etc/{{ dogtag }}'
    state: touch

- name: get date
  command: 'date --iso-8601'
  register: build_date

- name: write dogtag
  lineinfile:
    line: '{{ version.stdout }} {{ build_date.stdout }}'
    state: present
    path: '/etc/{{ dogtag }}'

- name: remove hostname
  file:
    path: /etc/hostname
    state: absent

- name: create hostname
  file:
    path: /etc/hostname
    state: touch

- name: set hostname
  lineinfile:
    path: /etc/hostname
    line: '{{ platform }}'

- name: set root password
  shell:
    cmd: "echo 'root:kamikaze' | chpasswd"

- name: force user to change debian password on first login
  shell:
    cmd: "chage -d 0 debian"
  when: platform != 'recore'

- name: force user to change root password on first login
  shell:
    cmd: "chage -d 0 root"
  when: platform != 'recore'

- name: create issue and issue.net file
  file:
    path: '{{ item }}'
    state: touch
  with_items:
   - /etc/issue
   - /etc/issue.net

- name: write issue and issue.net
  copy:
    dest: '{{ item }}'
    content: |
      {{ version.stdout }}

      Check that nothing is printing before any intensive operation!
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: enable ssh
  service:
    name: ssh
    enabled: yes

- name: remove connman
  apt:
    name: connman
    state: absent

- name: create resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch
    mode: 0644
    owner: root
    group: root

- name: reset the resolv.conf file
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver 1.1.1.1
    state: present

- name: install NetworkManager
  apt:
    name: network-manager
    state: latest

- name: Recore - fetch dtb and dts device trees
  when: platform == 'recore'
  get_url:
    url: "https://github.com/intelligent-agent/Recore/raw/master/Device_tree/{{ item }}"
    dest: "/boot/dtb/allwinner/{{ item }}"
  with_items:
    - sun50i-a64-recore-A2.dtb
    - sun50i-a64-recore-A2.dts
    - sun50i-a64-recore-A3.dtb
    - sun50i-a64-recore-A3.dts
    - sun50i-a64-recore-A4.dtb
    - sun50i-a64-recore-A4.dts

- name: Recore - rename dtb device tree file
  copy:
    src: /boot/dtb/allwinner/sun50i-a64-recore-A4.dtb
    dest: /boot/dtb/allwinner/sun50i-a64-recore.dtb
  when: platform == 'recore'

- name: Recore - Replace platform name
  replace:
    path: /etc/armbian-release
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp1: 'Pine64', replace: 'Recore'}
    - { regexp1: 'pine64', replace: 'recore'}
  when: platform == 'recore'
