---
- name: remove login info
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue.net
    - /etc/issue
    
- name: upgrade packages
  apt:
    upgrade: dist
    
- name: remove unneeded packages
  apt:
    pkg:
    - nginx
    - hostapd
    - libgtk3-common
    - grub
    - javascript-common
    state: absent
    autoremove: yes

- name: Replicape - update RCN scripts
  command:
    chdir: /opt/scripts
    cmd: 'git pull'
  when: platform == 'replicape'

- name: install debconf-utils and curl
  apt:
    pkg: 
      - debconf-utils
      - curl
      - firmware-realtek
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-pip
    - python3-pip
    - python-dev
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - unzip
    - cpufrequtils
    - pkg-config
    - python3-dev
    - pkg-config
    state: present
    autoremove: yes
    autoclean: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present
      
- name: remove unneeded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/
    - /root/.c9
    - /usr/lib/node_modules
    - /usr/local/lib/node_modules
    - /var/lib/cloud9
    - /var/cache/doc*

- name: create dogtag
  file:
    path: '/etc/{{ dogtag }}'
    state: touch

- name: get date
  command: 'date'
  register: build_date

- name: write dogtag
  lineinfile:
    line: '{{ version }} {{ build_date.stdout }}'
    state: present
    path: '/etc/{{ dogtag }}'

- name: remove hosts entry
  lineinfile:
    path: /etc/hostname
    line: arm
    state: absent

- name: set root password
  shell:
    cmd: "echo 'root:kamikaze' | chpasswd"

- name: force user to change password on first login
  shell:
    cmd: "chage -d 0 root"

- name: create issue and issue.net file
  file:
    path: '{{ item }}'
    state: touch
  with_items:
   - /etc/issue
   - /etc/issue.net

- name: write issue and issue.net
  blockinfile:
    path: '{{ item }}'
    state: present
    block: |
      "{{ version }}

      Check that nothing is printing before any intensive operation!
      "
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: enable ssh
  service:
    name: ssh
    enabled: yes

- name: enable connman
  service:
    name: connman
    enabled: yes
  when: platform == 'replicape'
