---
- name: install weston
  tags: weston
  apt:
    pkg:
      - weston

- name: make weston ini directory
  tags: weston
  file:
    path: /etc/xdg/weston
    state: directory
    mode: '0755'

- name: make weston ini file
  tags: weston
  copy:
    dest: /etc/xdg/weston/weston.ini
    content: |
      [core]
      idle-time=0

      [shell]
      locking=false
      panel-position=none

      [output]
      name=HDMI-A-1
      transform=0

- name: make weston service file
  tags: weston
  copy:
    dest: /etc/systemd/system/weston.service
    content: |
      [Unit]
      Description=Weston Wayland Compositor

      [Service]
      Environment="XDG_RUNTIME_DIR=/run/user/1000"
      ExecStart=/usr/bin/weston-launch --user debian

      [Install]
      WantedBy=multi-user.target

- name: Enable service weston
  shell: systemctl enable weston
